# Generated by Django 5.2 on 2025-04-30 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_checkquestion_checktest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.checktest'),
        ),
    ]
