# Generated by Django 5.2 on 2025-05-05 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_checkquestion_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
