# Generated by Django 5.2 on 2025-05-08 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_category_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Nomi', max_length=150),
        ),
        migrations.AlterField(
            model_name='questions',
            name='a',
            field=models.CharField(help_text='Variant A', max_length=150),
        ),
        migrations.AlterField(
            model_name='questions',
            name='b',
            field=models.CharField(help_text='Variant B', max_length=150),
        ),
        migrations.AlterField(
            model_name='questions',
            name='c',
            field=models.CharField(help_text='Variant C', max_length=150),
        ),
        migrations.AlterField(
            model_name='questions',
            name='d',
            field=models.CharField(help_text='Variant D', max_length=150),
        ),
        migrations.AlterField(
            model_name='questions',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.test'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.CharField(help_text='Savol nomi', max_length=250),
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.ForeignKey(help_text='Test turini tanlang', on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pass_percentage',
            field=models.PositiveBigIntegerField(help_text="O'tish foizi"),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(help_text='Test nomi', max_length=200),
        ),
    ]
